// ── app/layout.js ──
' useClient '
import { Geist, Geist_Mono }   from 'next/font/google';

// ✅ 1. Use the precise path ‘next-auth/next’.
//    Think of it like giving the mailman a street *and* apartment number
//    instead of just the building name.
import { getServerSession }    from 'next-auth/next';

import { authOptions }         from '../lib/authOptions';
import ClientProviders         from './ClientProviders';
import Layout                  from '../components/Layout';
import './globals.css';

/* Google fonts */
const geistSans = Geist({  variable: '--font-geist-sans',  subsets: ['latin'] });
const geistMono = Geist_Mono({ variable: '--font-geist-mono', subsets: ['latin'] });

export const metadata = {
  title:       'VybeLocal',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  // 2. Grab the current user session **on the server** –
  //    before the page even reaches the browser.
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* 3. Hand that session to everything inside our app */}
        <ClientProviders session={session}>
          <Layout>{children}</Layout>
        </ClientProviders>
      </body>
    </html>
  );
}